#!/bin/sh
# Alpine Linux genfstab

# default location for mounted root
SYSROOT=${SYSROOT:-/mnt}

USE_UUID=1

in_list() {
	local i="$1"
	shift
	while [ $# -gt 0 ]; do
		[ "$i" = "$1" ] && return 0
		shift
	done
	return 1
}

fstype_is_pseudofs() {
  # list taken from util-linux source: libmount/src/utils.c
  pseudofs_types='anon_inodefs autofs bdev binfmt_misc cgroup configfs cpuset 
	debugfs devfs devpts devtmpfs dlmfs fuse.gvfs-fuse-daemon fusectl 
	hugetlbfs mqueue nfsd none pipefs proc pstore ramfs rootfs rpc_pipefs 
	securityfs sockfs spufs sysfs tmpfs efivarfs'
  in_list $1 $pseudofs_types
}

# wrapper to only show given device
_blkid() {
	blkid | grep "^$1:"
}

# if given device have an UUID display it, otherwise return the device
uuid_or_device() {
	local i=
	case "$1" in
		/dev/md*) echo "$1" && return 0;;
	esac
	test -z "$USE_UUID" && echo "$1" &&return 0

	for i in $(_blkid "$1"); do
		case "$i" in
			UUID=*) eval $i;;
		esac
	done
	if [ -n "$UUID" ]; then
		echo "UUID=$UUID"
	else
		echo "$1"
	fi
}

# generate an fstab from a given mountpoint. Convert to UUID if possible
enumerate_fstab() {
	local mnt="$1"
	local fs_spec= fs_file= fs_vfstype= fs_mntops= fs_freq= fs_passno=
	[ -z "$mnt" ] && return
	local escaped_mnt=$(echo $mnt | sed -e 's:/*$::' -e 's:/:\\/:g')
	awk "\$2 ~ /^$escaped_mnt(\/|\$)/ {print \$0}" /proc/mounts | \
		sed "s:$mnt:/:g; s: :\t:g" | sed -E 's:/+:/:g' | \
		while read fs_spec fs_file fs_vfstype fs_mntops fs_freq fs_passno; do
			if [ -z "$USE_PSEUDOFS" ] && fstype_is_pseudofs "$fs_vfstype"; then
				continue
			fi
			echo -e "$(uuid_or_device $fs_spec)\t${fs_file}\t${fs_vfstype}\t${fs_mntops} ${fs_freq} ${fs_passno}"
		done

}

enumerate_fstab "$SYSROOT"

EFI_GUID=$(dd bs=1 skip=67 count=4 if=/dev/sda1 2> /dev/null | xxd -p | sed -r 's/(..)(..)(..)(..)/\4\3-\2\1/' | cut -c -9)
echo -e "UUID=$EFI_GUID\t\t\t\t/boot/efi\tvfat\trw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,utf8,errors=remount-ro\t0 2"

echo -e "\tnone\tswap\tdefaults\t0 0"
echo -e "\t\t\t\t\t\t/tmp\ttmpfs\trw,nodev,nosuid,siwe=2G\t0 0"

blkid
